/* Generated By:JavaCC: Do not edit this line. DFA_GeneratorTreeConstants.java Version 5.0 */
package parser;

public interface DFA_GeneratorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTPAR = 4;
  public int JJTID = 5;
  public int JJTTIMES = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "OR",
    "AND",
    "PAR",
    "ID",
    "TIMES",
  };
}
/* JavaCC - OriginalChecksum=49cb0b7942508a0db5fa509fc681c3af (do not edit this line) */
