/* Generated By:JavaCC: Do not edit this line. DFA_GeneratorTreeConstants.java Version 5.0 */
public interface DFA_GeneratorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTPAR = 4;
  public int JJTID = 5;
  public int JJTTIMES = 6;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "OR",
    "AND",
    "PAR",
    "ID",
    "TIMES",
  };
}
/* JavaCC - OriginalChecksum=0e3892e02cca8b5dbe6b7b6e67c8d0e6 (do not edit this line) */
