/* Generated By:JJTree&JavaCC: Do not edit this line. DFA_GeneratorConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DFA_GeneratorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 4;
  /** RegularExpression Id. */
  int IDENTIFIER = 5;
  /** RegularExpression Id. */
  int SEPARATOR = 6;
  /** RegularExpression Id. */
  int OR = 7;
  /** RegularExpression Id. */
  int ONE_OR_MORE = 8;
  /** RegularExpression Id. */
  int ZERO_OR_MORE = 9;
  /** RegularExpression Id. */
  int ZERO_OR_ONE = 10;
  /** RegularExpression Id. */
  int LEFT_PAR = 11;
  /** RegularExpression Id. */
  int RIGHT_PAR = 12;
  /** RegularExpression Id. */
  int NLINE = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<NUMBER>",
    "<IDENTIFIER>",
    "\".\"",
    "\"|\"",
    "\"+\"",
    "\"*\"",
    "\"?\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\"{\"",
    "\",\"",
    "\"}\"",
  };

}
