/* Generated By:JavaCC: Do not edit this line. DFA_GeneratorTreeConstants.java Version 5.0 */
public interface DFA_GeneratorTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPR_MAIN = 1;
  public int JJTEXPR_CONCAT = 2;
  public int JJTEXPR_TIMES = 3;


  public String[] jjtNodeName = {
    "Start",
    "Expr_Main",
    "Expr_Concat",
    "Expr_Times",
  };
}
/* JavaCC - OriginalChecksum=438a32834bb5dbfd3a2b07b8c481e962 (do not edit this line) */
