/* Generated By:JavaCC: Do not edit this line. RegexParserTreeConstants.java Version 5.0 */
package parser;

public interface RegexParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTID = 4;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "OR",
    "AND",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=b93809800144da5e57fc2c622b2263d9 (do not edit this line) */
